---
title: "Testing Notebook"
author: Noam Ross
date: 2016-10-14-
output: html_document
bibliography: references.bib
csl: elsevier-with-titles.csl
link-citations: true
---

```{r setup, include=FALSE}
library(knitcitations)
cite_options(citation_format = 'pandoc')
P <- rprojroot::find_rstudio_root_file
```

```{r setup2}
library(metaflu)
library(ggplot2)
library(parallel)
library(dplyr)
```

Set parameters for the simulator.  For now, no real network - just two unconnected
patches

```{r}
try_parms = list(
  beta = 0.004,                     #contact rate for direct transmission
  gamma = 0.167,                    #recovery rate
  mu = 0,                           #base mortality rate
  alpha = 0,                        #disease mortality rate
  phi = 1.96e-4,                    #infectiousness of environmental virions
  eta = 0.14,                       #degradation rate of environmental virions
  nu =  0.001,                      #uptake rate of environmental virion
  sigma = 1000, # 1e5,                      #virion shedding rate
  omega = 0,                        #movement rate
  chi = matrix(c(1,0,0,1), nrow=2), #patch connectivity matrix. Ignored if network_type is provided
  network_type =  "smallworld",     #type of network to generate (from igraph)
  network_parms = list(dim=1, size=64, nei=2.33, p=0.0696), #named parameters for the igraph network generation function
  stochastic_network = FALSE        #generate a new network each time?
)

initial_cond <- matrix(c(500, 0, 0, 0),
                         nrow=64, ncol=4, byrow=TRUE)
infected_patches <- sample(seq_len(nrow(initial_cond)), 2)
initial_cond[infected_patches, 2] <- 1
initial_cond[infected_patches, 1] <- initial_cond[infected_patches, 1] - 1
```

Run the simulator and plot

```{r runsim}
options(mc.cores=2)
output1 <- mf_sim(init = initial_cond, parameters = try_parms, times=0:1000, n_sims = 1,  parallel = FALSE)
#output2 <- mf_sim(init = initial_cond, parameters = try_parms, times=0:1000, n_sims = 2, seed = 2, parallel = TRUE)
#output3 <- mf_sim(init = initial_cond, parameters = try_parms, times=0:1000, n_sims = 2, parallel = FALSE)

outputs = output1 %>% 
  filter(class == "I") %>% 
  group_by(sim, time) %>% 
  summarize(infecteds = sum(population)) %>% 
  group_by()

ggplot(outputs, aes(x=time, y=infecteds, group=sim)) +
  geom_line(alpha=0.1)
```



```{r, include=FALSE}
write.bibtex(file=P("notebook/references.bib"))
```

## References

<div id="refs"></div>
