---
title: "Parameters"
bibliography: references.bib
csl: elsevier-with-titles.csl
link-citations: true
output:
  html_document:
    keep_md: TRUE
---

```{r setup, include=FALSE}
library(knitcitations)
cite_options(citation_format = 'pandoc')
P <- rprojroot::find_rstudio_root_file
```

###Questions

__Movement Rate ($\omega$)__

- How often do small / large farms exchange chickens?

- How many chickens are at a market?

- How many people would be at a market?

- Do chickens that go to market return to farms?

__Network__

- Is a large farm realistically one large node, or a clustering of small nodes?

- If large farms have separate sections, how are they connected and what are the movement patterns between sections?

__Culling Parameters ($\tau$, $\iota$, $\pi$, t-detect)__

- How long does it take between knowing a farm is infected and culling the farm?

- How common is it for a farmer to report an infected farm?

- What is a realistic threshold of deaths or infections for a farmer to notice a problem? What is a realistic time frame for this process?

- What is the actual culling protocol?

- Is there government oversight?

- Is there some standard culling procedure?

- How good are your diagnostic tools? Are there false alarms? (to get at pi-detect)

__Direct Transmission ($\beta$, $\rho$)__

- How does transmission change per strain?

- How does it change based on farm size?

__Recovery Rate ($\gamma$)__ 

- What is the recovery rate per strain?

- Does this change based on farm size (due to attention / resources)? 

__Base Mortality Rate ($\mu$)__

- What is the base mortality rate for chickens?

- Does this change in different locales?

- Does this differ based on the size or type of farm (due to attention / resources)?

__Disease Mortality Rate ($\alpha$)__

- What is the disease mortality per strain?

- Does the disease mortality change during the course of an outbreak?



###Previous Model Parameters `r citep('10.1371/journal.pone.0080091')`:

Direct Transmission $\beta = 0.004$  

Recovery Rate $\upsilon = (0-0.167)$

Disease Mortality Rate $\alpha = (0 - 0.4)$

Environmental Uptake Rate $\nu = 0.001$

Virion Infectiousness $\phi = 1.96 * 10^{-4}$

Virus Degradation Rate $\eta = 0.14$

Virion Shedding Rate $\sigma = 10^5$

Movement Rate $\omega = 0.30$


## References

<div id="refs"></div>
