---
title: "Paper Results Reproduction"
author: Cale Basaraba
date: 2016-11-7
output: html_document
bibliography: references.bib
csl: elsevier-with-titles.csl
link-citations: true
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(cache.path='~/.vignette_cache/')
library(knitcitations)
cite_options(citation_format = 'pandoc')
P <- rprojroot::find_rstudio_root_file
```

Model after `r citep('10.1371/journal.pone.0080091')`.

```{r setup2}
library(metaflu)
library(ggplot2)
library(dplyr)
library(doMC)
```

Set parameters for the simulator.  For now, no real network - just two unconnected
patches

```{r}
registerDoMC(cores=2)
parms = list(
  beta = 0.004,   #contact rate for direct transmission
  gamma = 0.167,  #recovery rate
  mu = 0,         #base mortality rate
  alpha = 0,      #disease mortality rate
  phi = 1.96e-4,  #infectiousness of environmental virions
  eta = 0.14,     #degradation rate of environmental virions
  nu =  0.001,    #uptake rate of environmental virion
  sigma = 0,      #virion shedding rate
  omega = 0,      #movement rate
  rho = 0,        #contact  nonlinearity 0=dens-dependent, 1=freq-dependent
  lambda = 0,    #force of infection from external sources
  chi = matrix(c(0,0,0,0), nrow=2)  #patch connectivity matrix
  )

initial_cond <- matrix(c(100, 0, 0, 0), nrow=64, ncol=4, byrow=TRUE)

infected_patches <- sample(seq_len(nrow(initial_cond)), 2)
initial_cond[infected_patches, 2] <- 1
initial_cond[infected_patches, 1] <- initial_cond[infected_patches, 1] - 1

paperparms = list(
  beta = 0.004,   #contact rate for direct transmission
  gamma = 0.167,  #recovery rate
  mu = 0,         #base mortality rate
  alpha = 0.4,      #disease mortality rate
  phi = 1.96e-4,  #infectiousness of environmental virions
  eta = 0.14,     #degradation rate of environmental virions
  nu =  0.001,    #uptake rate of environmental virion
  sigma = 0,      #virion shedding rate
  omega = 0.3,      #movement rate
  rho = 0,        #contact  nonlinearity 0=dens-dependent, 1=freq-dependent
  lambda = 0,    #force of infection from external sources
  chi = matrix(c(1,0,0,1), nrow = 2, ncol = 2),
  network_type = "smallworld",
  network_parms = list(dim = 3, size = 2, nei = 1, p = 0.1, multiple = TRUE, loops = FALSE)
)



```

Run the simulator and plot

```{r runsim, cache=TRUE}
output2 <- mf_sim(init = initial_cond, parameters = paperparms, times=0:1000, n_sims = 100)

outputs = output2 %>% 
  filter(class == "I") %>% 
  group_by(sim, time) %>% 
  summarize(infecteds = sum(population)) %>% 
  group_by()

ggplot(outputs, aes(x=time, y=infecteds, group=sim)) +
  geom_line(alpha=0.1)


library(igraph)
test_net <- make_net(paperparms[["network_type"]], paperparms[["network_parms"]])

test_ws <- do.call(paste0("sample_",paperparms[["network_type"]]),paperparms[["network_parms"]])

plot(test_ws, layout = layout.circle)

```

```{r learning-igraph}
library(igraph)

x <- list(dim = 3, size = 4, nei = 2.33, p = 0.0596)
net <- as_adj(do.call("sample_smallworld", x),
               sparse=FALSE)

#there are size^dim vertices in base graph, with nei initial connections

sw <- do.call("sample_smallworld",x)

plot(sw)

```



```{r, include=FALSE}
write.bibtex(file="references.bib")
```

## References

<div id="refs"></div>
