---
title: "Presentation Notes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(metaflu)
library(ggplot2)
library(dplyr)
library(doMC)
library(foreach)
library(tidyr)
library(purrr)
library(gridExtra)
library(abind)
#registerDoMC(cores = 20)
#devtools::install_github("renozao/doRNG", force = TRUE)
library(doRNG)
set.seed(123)
P <- rprojroot::find_package_root_file

```

### Basic Run No Culling

```{r basic-run}
number_of_farms <- 200
number_of_chickens <- 50

  parms = list(
    beta = 1.44456,   #contact rate for direct transmission
    gamma = 0.167,  #recovery rate
    mu = 0,         #base mortality rate
    alpha = 0.4,      #disease mortality rate
    phi = 0,  #infectiousness of environmental virions
    eta = 0,     #degradation rate of environmental virions
    nu =  0.00,    #uptake rate of environmental virion
    sigma = 0,      #virion shedding rate
    omega = 0.03,   #movement rate
    rho = 0.85256,        #contact  nonlinearity 0=dens-dependent, 1=freq-dependent
    lambda = 0,     #force of infection from external sources
    tau_crit = 5,   #critical suveillance time
    I_crit = 5,     #threshold for reporting
    pi_report = 0, #reporting probability
    pi_detect = 0, #detection probability
    cull_time = 10,#time to culling
    network_type = "smallworld",
    network_parms = list(dim = 1, size = number_of_farms, nei = 2.33, p = 0.0596, multiple = FALSE, loops = FALSE),
    stochastic_network = TRUE
    )
  
#create patches
sims <- 10

initial_cond_list <- lapply(seq_len(sims), function(x){
  return(basic_patches(number_of_chickens, number_of_farms))
})

base_seeded_list <- lapply(initial_cond_list, function(x){
  return(seed_initial_infection(x))
})

network_list <- lapply(seq_len(sims), function(x){
  return(make_net(parms$network_type, parms$network_parms))
})

basic_results_list <- map2(base_seeded_list,network_list, function(x,y){
  parms$chi <- y
  return(mf_sim(init = x, parameters = parms, times = 1:365))
})

basic_results <- do.call("abind", basic_results_list)
  
rm(basic_results_list)
gc()

```

```{r visualize}

create_graph_panel(basic_results)

```

### Random Growth Run No Culling

```{r growth-no-culling}
growth_cond_list <- lapply(initial_cond_list, function(x){
  return(grow_patches_random(x))
})

growth_seeded_list <- lapply(growth_cond_list, function(x){
  return(seed_initial_infection(x))
})

random_growth_list <- map2(growth_seeded_list, network_list, function(x,y){
  parms$chi <- y
  return(mf_sim(init = x, parameters = parms, times = 1:365))
})

random_growth <- do.call("abind", random_growth_list)

rm(random_growth_list)
gc()

```

```{r visualize-gnc}
create_graph_panel(random_growth)

```

### Localized Growth Run No Culling

```{r lgrowth-no-culling}
growth_cond_list <- lapply(initial_cond_list, function(x){
  return(grow_patches_random(x))
})

growth_seeded_list <- lapply(growth_cond_list, function(x){
  return(seed_initial_infection(x))
})

random_growth_list <- map2(growth_seeded_list, network_list, function(x,y){
  parms$chi <- y
  return(mf_sim(init = x, parameters = parms, times = 1:365))
})

random_growth <- do.call("abind", random_growth_list)

rm(random_growth_list)
gc()

```

```{r visualize-gnc}
create_graph_panel(random_growth)

```


