---
title: "Doubling Scenario - Initial Infection"
author: "Cale Basaraba"
date: "3/23/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = TRUE)
library(metaflu)
library(ggplot2)
library(dplyr)
library(doMC)
library(tidyr)
library(purrr)
```

```{r patch-functions}

basic_patches <- function(farm_size, farm_number){
  initial_cond <- cbind(rpois(farm_number, farm_size), matrix(0, ncol = 3, nrow = farm_number))
  return(initial_cond)
}

growth_nodes <- function(farm_size, farm_number){
  nodes <- c(rpois(round(farm_number*8/9,0), farm_size), rpois(round(farm_number/9, 0), farm_size*10))
  total <- cbind(nodes, matrix(0, ncol = 3, nrow = length(nodes)))
  total <- total[sample(nrow(total)),]
  return(total)
}

grow_patches <- function(basic_cond){
  s_num <- round(nrow(basic_cond)*1/11)
  new_cond <- basic_cond
  grow_rows <- sample.int(nrow(new_cond), s_num)
  walk(grow_rows, function(row){
    new_cond[row,1] <- new_cond[row,1]*10
  })
  return(new_cond)
}

```

```{r network-setup}
#Set number of farms and ~ number of chickens per farm
farm_number <- 100
farm_size <- 15

#Make network connections
set.seed(123)
network_type <- "smallworld"
network_parms <- list(dim = 1, size = farm_number, nei = 2.33, p = 0.0596, multiple = FALSE, loops = FALSE)
nw <- make_net(network_type, network_parms)

#Set up patch size
initial_cond <- basic_patches(farm_size, farm_number)
  infected_patches <- sample(seq_len(nrow(initial_cond)), 1)
  initial_cond[infected_patches, 2] <- 1
  initial_cond[infected_patches, 1] <- initial_cond[infected_patches, 1] - 1

```

```{r parameter-setup}
  parms = list(
    beta = 0.004,   #contact rate for direct transmission
    gamma = 0.167,  #recovery rate
    mu = 0,         #base mortality rate
    alpha = 0.4,      #disease mortality rate
    phi = 0,  #infectiousness of environmental virions
    eta = 0,     #degradation rate of environmental virions
    nu =  0.00,    #uptake rate of environmental virion
    sigma = 0,      #virion shedding rate
    omega = 0.03,   #movement rate
    rho = 0,        #contact  nonlinearity 0=dens-dependent, 1=freq-dependent
    lambda = 0,     #force of infection from external sources
    tau_crit = 0,   #critical suveillance time
    I_crit = 0,     #threshold for reporting
    pi_report = 0, #reporting probability
    pi_detect = 0, #detection probability
    chi = nw       #network connections created in above step
    )
```


```{r basic-run}
basic_results <- mf_sim(init = initial_cond, parameters = parms, times=0:100, n_sims = 100, return_array=FALSE)
durations <- get_duration(basic_results)

s <- get_susceptibles(basic_results)
i <- get_infections(basic_results)
r <- get_recovered(basic_results)

spread_failures <- get_failure(basic_results)

tot_i <- get_tot_infections(basic_results)
```

```{r growth-run}
#Grow a random number of patches to get double total chicken population
grown_cond <- grow_patches(initial_cond)

grown_results <- mf_sim(init = grown_cond, parameters = parms, times = 0:100, n_sims = 100, return_array= FALSE)

g_durations <- get_duration(grown_results)

g_s <- get_susceptibles(grown_results)
g_i <- get_infections(grown_results)
g_r <- get_recovered(grown_results)

g_spread_failures <- get_failure(grown_results)

g_tot_i <- get_tot_infections(grown_results)

```

