// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// sim_gillespie
arma::mat sim_gillespie(const arma::vec& init, const List parmlist, const arma::vec& times, const bool& progress);
RcppExport SEXP metaflu_sim_gillespie(SEXP initSEXP, SEXP parmlistSEXP, SEXP timesSEXP, SEXP progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type init(initSEXP);
    Rcpp::traits::input_parameter< const List >::type parmlist(parmlistSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type times(timesSEXP);
    Rcpp::traits::input_parameter< const bool& >::type progress(progressSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_gillespie(init, parmlist, times, progress));
    return rcpp_result_gen;
END_RCPP
}
