# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sim_gillespie <- function(init, parmlist, times, progress, abort) {
    .Call('_metaflu_sim_gillespie', PACKAGE = 'metaflu', init, parmlist, times, progress, abort)
}

